README.md

Translated readme

---

LICENSE
package.json

Add license to project

---

package-lock.json
package.json
resources/style.css
src/api/tmc.ts
src/config/storage.ts
src/extension.ts
src/init.ts
src/test/config/storage.test.ts
src/ui/ui.ts

Resolves #28  
Resolves #29  
Resolves #30  
Resolves #31

Implement oauth

---

.github/workflows/nodejs.yml

Windows ci

---

package-lock.json
package.json
src/api/tmc.ts
tslint.json

Add support for requesting organizations, courses and course details

---

package-lock.json
package.json
src/api/tmc.ts
src/errors.ts
src/init.ts

Error refactor

---

src/api/tmc.ts

Use template strings for API paths

---

package-lock.json
package.json
src/api/tmc.ts
src/errors.ts
tsconfig.json

Add runtime type checking for TMC API responses

---

package-lock.json
src/init.ts
src/test/ui/visibility.test.ts
src/ui/treeview/treeview.ts
src/ui/treeview/visibility.ts
src/ui/ui.ts

Treeview visibility rework

---

src/api/tmc.ts
src/api/types.ts
src/extension.ts
src/init.ts
src/utils.ts

Fixes #57 and resolves #58 
Also resolves #59 and closes #60

Download files

---

src/init.ts
src/ui/treeview/treeview.ts

Support programmatically triggering callbacks

---

resources/style.css
resources/templates/course.html
resources/templates/organization.html
src/api/tmc.ts
src/api/types.ts
src/init.ts

Courseview

---

.vscode/settings.json
resources/styles/style.css
resources/templates/course-details.html
resources/templates/index.html
resources/templates/loading.html
src/api/tmc.ts
src/init.ts
src/utils.ts

Resolves #75 
Resolves #62 
Resolves #67

Download multiple exercises at once

---

package-lock.json
package.json
src/api/tmc.ts
src/api/types.ts
src/extension.ts

MVP-level solution for submitting exercises

---

resources/styles/style.css
resources/templates/course-details.html

Fix the white background from bootstrap to match the selected VSCode theme.
https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content

Fix styling of editor view to match selected theme

---

src/extension.ts
src/init.ts
src/ui/treeview/actions.ts
src/ui/treeview/handlers.ts
src/ui/treeview/types.ts

Refactor init.ts

---

package.json
resources/templates/test-result.html
src/config/resources.ts
src/extension.ts
src/init.ts
src/ui/temporaryWebview.ts
src/ui/ui.ts
src/ui/webview.ts

Resolves #81 
Resolves #84 
Resolves #86

Add ability to run exercise tests locally

---

package-lock.json
package.json

Make `typescript-is` a runtime dependency.

Fix production dependensies

---

resources/styles/style.css
resources/templates/test-result.html
src/api/tmc.ts
src/api/types.ts
src/extension.ts
src/utils.ts

Get submission results from server

---

resources/styles/style.css
resources/templates/test-result.html
src/ui/templateEngine.ts

Local test result styling

---

resources/templates/course-details.html
src/api/exerciseManager.ts
src/api/tmc.ts
src/config/resources.ts
src/config/storage.ts
src/extension.ts
src/init.ts
src/test/config/storage.test.ts
src/ui/treeview/actions.ts
src/ui/treeview/handlers.ts
src/utils.ts

Workspace rework

---

resources/templates/submission-result.html
resources/templates/submission-status.html
resources/templates/test-result.html
src/extension.ts
src/ui/templateEngine.ts

Add an progress bar for run test locally and submission. Clean up code.

Progress bar

---

src/extension.ts

Submission webview improvements

---

resources/templates/login.html
src/ui/treeview/handlers.ts

Closes #104 
Note that removing the form completely causes the submission to be aborted

Login improvements

---

resources/styles/style.css
resources/templates/course.html
resources/templates/organization.html

Fix bg white on logos

---

src/api/exerciseManager.ts
src/api/tmc.ts
src/extension.ts

TMC doesn't create ExerciseManager

---

resources/templates/test-result.html
src/extension.ts
src/ui/templateEngine.ts

Fixes #111 
TODO: Refactor vscode.commands.registerCommand("uploadArchive"... to be called with exercise ID.

Run in background for tests, if passed, submit to server noti

---

.gitignore
.vscode/launch.json
.vscodeignore
package-lock.json
package.json
webpack.config.js

Webpack init

---

resources/templates/submission-result.html
src/api/types.ts
src/ui/templateEngine.ts

Resolves #109 
pre-tag color will be fixed once it is merged to master.

Submission compile failed error

---

resources/styles/style.css
resources/templates/submission-result.html
resources/templates/submission-status.html
src/extension.ts
src/ui/templateEngine.ts
src/ui/temporaryWebview.ts

Resolves #137 
Resolves #135 
Resolves #138 
Resolves #136

Fix line breaks, buttons for result, temp reveal panel function, refactor

---

resources/templates/running-tests.html
resources/templates/test-result.html
src/extension.ts
src/ui/templateEngine.ts
src/ui/temporaryWebview.ts

resolves #142
resolves #144 
+ can run local tests in background

submit to server button in tests-result, run in background button in running-tests

---

resources/templates/submission-result.html
src/extension.ts
src/ui/templateEngine.ts

View model solution and notification if submission long in queue

---

resources/templates/test-result.html
src/actions/actions.ts
src/ui/templateEngine.ts
src/ui/temporaryWebview.ts

#133 Add the button to call the function 
Passing tempview panel to submitExercise if the button is pressed.

Submit to server button, passing tempview panel object

---

resources/templates/login.html
src/actions/actions.ts

Style for login webview

---

resources/styles/style.css
resources/templates/course.html
resources/templates/index.html
resources/templates/organization.html

Fix styling errors, center organization images, remove unnecessary text

---

src/init.ts

Remove add new course from navi

---

resources/templates/running-tests.html
src/api/tmc.ts
src/api/workspaceManager.ts

Fix styling and reset exercise

---

resources/templates/submission-result.html

Have some notification when feedback is sent or not given.

Feedback notification

---

resources/templates/loading.html
resources/templates/running-tests.html

Add spinners to loading screens

---

src/extension.ts
src/init.ts
src/utils.ts

Check if java can be run during startup or abort

---

resources/templates/course-details.html
resources/templates/course.html
resources/templates/download-exercises.html
resources/templates/downloading-exercises.html
resources/templates/index.html
resources/templates/loading.html
resources/templates/login.html
resources/templates/organization.html
resources/templates/running-tests.html
resources/templates/submission-result.html
resources/templates/submission-status.html
resources/templates/test-result.html
src/ui/templateEngine.ts

Fixed css style loading. Now it does it consistently before loading anything else on the site.

Css load fix

---

resources/templates/course-details.html
resources/templates/download-exercises.html
src/actions/webview.ts

Sorting download exercises

---

CHANGELOG.md
README.md
package.json
resources/templates/course-details.html
resources/templates/download-exercises.html
src/actions/webview.ts
src/actions/workspace.ts
src/api/tmc.ts
src/api/workspaceManager.ts
src/config/types.ts
src/config/validate.ts
src/init.ts
src/test/config/storage.test.ts
src/utils.ts

Fixes #223 
Fixes #248 - commit: 9ee3c42

Development trunk

---

.eslintrc.json
CHANGELOG.md
resources/templates/course-details.html
resources/templates/download-exercises.html
resources/templates/index.html
src/actions/user.ts
src/actions/webview.ts
src/api/workspaceWatcher.ts
src/config/validate.ts
src/ui/temporaryWebview.ts

Consistent temp webview behavior, courseview UI fixes

---

CHANGELOG.md
package-lock.json
package.json
src/actions/user.ts

Removes exercises with status missing, i.e. they are not closed/opened, from the storage.

Remove exercises from storage on course deletion with status missing

---

.vscodeignore
CHANGELOG.md
media/menu.svg
media/test.svg
package.json

Added icons for running tests and menu

---

CHANGELOG.md
resources/templates/test-result.html
src/ui/templateEngine.ts

Showing first failed test, show all button

---

CHANGELOG.md
package-lock.json
package.json
resources/styles/style.css
src/actions/user.ts
src/config/constants.ts
src/utils/index.ts
src/utils/testResultParsing.ts

Release 0.5.1

---

CHANGELOG.md
package-lock.json
package.json
src/actions/types.ts
src/actions/user.ts
src/actions/webview.ts
src/config/validate.ts
src/extension.ts
src/test/ui/temporaryWebviewProvider.test.ts
src/ui/templateEngine.ts
src/ui/templates/CourseDetails.jsx
src/ui/temporaryWebview.ts
src/ui/temporaryWebviewProvider.ts
src/ui/types.ts

Reuse tempviews

---

src/actions/user.ts
src/api/tmc.ts
src/api/types.ts
src/config/constants.ts
src/config/resources.ts
src/config/settings.ts
src/extension.ts
src/init/resources.ts
src/ui/templateEngine.ts

Implement TMC Langs Rust for local tests

---

.eslintrc.json
CHANGELOG.md
config.js
package-lock.json
package.json
src/ui/templates/CourseDetails.jsx

Fixes #430 
Use existing tmc-langs-rust version in production.

0.9.2: Fix new badges shown as expired

---

.eslintrc.json
package.json
resources/templates/index.html
src/actions/types.ts
src/actions/user.ts
src/actions/webview.ts
src/actions/workspace.ts
src/api/tmc.ts
src/api/vscode.ts
src/api/workspaceManager.ts
src/api/workspaceWatcher.ts
src/config/constants.ts
src/config/resources.ts
src/config/settings.ts
src/extension.ts
src/init/commands.ts
src/init/index.ts
src/init/resources.ts
src/init/settings.ts
src/init/ui.ts
src/ui/templates/CourseDetails.jsx
src/ui/types.ts
src/utils/logger.ts
src/utils/utils.ts

Resolves #386 
Fixes #435 
Needs testing before merge and release.

Workspace refactor

---

.eslintignore
.gitignore
src/init/ui.ts
src/ui/templates/CourseDetails.jsx

Add possibility to download individual exercises

---

package.json
src/actions/index.ts
src/init/commands.ts

Add command for workspace switching

---

src/api/tmc.ts

`downloadExercise`, initial code for `downloadOldExercise` of issue #437

Insiders: download exercises using langs

---

package.json
src/actions/index.ts
src/actions/workspace.ts
src/api/tmc.ts
src/init/commands.ts

Clean command

---

src/api/workspaceManager.ts
src/init/index.ts

Add recommendations to workspace files

---

src/init/resources.ts

Initialize workspace files after other resources

---

webpack.config.js

Fixes problems with compilation

Make dev and prod configs functions

---

config.js
package.json
resources/templates/error.html
src/actions/user.ts
src/actions/workspace.ts
src/api/tmc.ts
src/api/vscode.ts
src/api/workspaceManager.ts
src/config/resources.ts
src/config/storage.ts
src/config/userdata.ts
src/init/commands.ts
src/init/index.ts
src/init/ui.ts
src/ui/templateEngine.ts
src/utils/utils.ts

Handle API errors

---

.vscode/settings.json
CHANGELOG.md
config.js
package-lock.json
package.json
src/actions/user.ts
src/actions/workspace.ts
src/api/workspaceManager.ts
src/config/userdata.ts
src/errors.ts
src/init/commands.ts
src/init/index.ts
src/init/resources.ts
src/init/ui.ts

Release 0.10.0 PR

---

docs/FAQ.md
package.json
src/ui/templates/Welcome.jsx

Initial FAQ

---

resources/templates/settings.html
src/init/ui.ts

Button to open vscode extension logs folder

---

src/actions/user.ts
src/actions/webview.ts
src/config/userdata.ts
src/init/ui.ts

Refactor updateCourse, type safety improvements

---

package.json
src/actions/user.ts
src/actions/webview.ts
src/api/tmc.ts
src/extension.ts
src/init/commands.ts
src/ui/templates/CourseDetails.jsx
src/ui/templates/MyCourses.jsx
src/ui/types.ts

Logged in context for actions

---

README.md
backend/controllers/application.ts
backend/controllers/index.ts
backend/index.ts
backend/setup.ts
config.js
package.json
resources/templates/settings.html
resources/templates/submission-status.html
src/actions/user.ts
src/actions/workspace.ts
src/api/tmc.ts
src/api/types.ts
src/api/workspaceManager.ts
src/config/constants.ts
src/config/resources.ts
src/config/settings.ts
src/config/storage.ts
src/config/types.ts
src/config/userdata.ts
src/config/validate.ts
src/extension.ts
src/init/resources.ts
src/init/settings.ts
src/init/ui.ts
src/test/config/storage.test.ts
src/ui/templateEngine.ts
src/ui/types.ts
src/utils/env.ts
webpack.config.js

Resolves #477 
Resolves #478 
Resolves #481

TMC-Langs Rust API

---

src/api/tmc.ts

Obfuscate email and access token from logging

---

resources/templates/submission-status.html
src/actions/user.ts
src/actions/workspace.ts
src/api/tmc.ts
src/api/types.ts
src/extension.ts
src/init/commands.ts
src/utils/utils.ts

Remove Workspacemanager dependency from TMC class, refactor

---

src/actions/user.ts
src/config/validate.ts

Use courseData in validate and add new course

---

src/api/tmc.ts
src/config/validate.ts
src/extension.ts
src/init/resources.ts

Remove Insider from python executable path

---

CHANGELOG.md
package-lock.json
package.json
src/actions/user.ts
src/actions/workspace.ts
src/init/commands.ts
src/init/ui.ts

Separate new and update download actions

---

package.json
src/api/workspaceManager.ts
src/init/commands.ts

Add commands to vscode editor context

---

resources/templates/settings.html
src/commands/updateExercises.ts
src/config/settings.ts
src/config/types.ts
src/init/settings.ts
src/init/ui.ts
src/test/config/storage.test.ts

Add setting to download exercise updates automatically

---

src/actions/user.ts
src/actions/webview.ts
src/actions/workspace.ts
src/commands/showWelcome.ts
src/init/index.ts
src/init/ui.ts
src/ui/webview.ts

Derive webview message keys from command data

---

config.js
src/api/tmc.ts
src/api/types.ts
src/commands/wipe.ts
src/ui/templateEngine.ts

Langs update

---

config.js
package.json
src/api/tmc.ts
src/init/commands.ts
src/init/ui.ts
src/utils/env.ts
src/window/dialog.ts

Resolves #548
Resolves #550
Resolves #545

Handle warnings, open tmc exercises folder, add darwin arm64 support

---

src/api/tmc.ts

Show warning without callback

---

.gitignore
backend/index.ts
backend/package-lock.json
backend/package.json
backend/setup.ts
backend/utils.ts
src/test/api/tmc.test.ts

Test downloadExercise, downloadOldSubmission, resetExercise

---

src/api/workspaceManager.ts
src/config/resources.ts
src/extension.ts

Don't recommend missing extensions on VSCodium

---

src/actions/user.ts
src/api/tmc.ts
src/commands/pasteExercise.ts
src/commands/submitExercise.ts
src/config/constants.ts
src/errors.ts
src/test/api/tmc.test.ts

Too frequent submissions cause error

---

src/ui/templates/CourseDetails.jsx

Fix possibility of attempted disabled downloads

---

src/actions/types.ts
src/actions/user.ts
src/api/exerciseDecorationProvider.ts
src/config/constants.ts
src/config/userdata.ts
src/extension.ts
src/test/actions/checkForExerciseUpdates.test.ts
src/test/actions/moveExtensionDataPath.test.ts
src/test/actions/refreshLocalExercises.test.ts
src/test/api/exerciseDecorationProvider.test.ts
src/test/commands/cleanExercise.test.ts
src/test/fixtures/userData.ts
src/test/fixtures/workspaceManager.ts
src/test/mocks/actionContext.ts
src/test/mocks/userdata.ts
src/test/mocks/workspaceManager.ts

Decorate exercises

---

bin/validateRelease.sh
bin/verifyThatLangsBuildsExist.js
src/utils/env.d.ts
src/utils/env.js

Verify langs binaries exist before release

---

config.js
src/actions/workspace.ts
src/api/langsSchema.ts
src/api/tmc.ts
src/migrate/migrateExerciseData.ts
src/test-integration/tmc_langs_cli.spec.ts
src/test/actions/downloadOrUpdateExercises.test.ts
src/test/migrate/migrateExerciseData.test.ts

TMC-langs cli update

---

src/actions/user.ts
src/extension.ts
src/ui/ui.ts

Remove barely used status bar
